version: '1.0'

services:
  frontend:
    image: vite_app:1.0
    ports:
      - "5173:5173"
    build:
      context: ./front-end  # Path to the directory containing the Dockerfile

  backend:
    image: flask_app:1.1
    ports:
      - "5000:5000"
    build:
      context: ./flask_app   # Path to the directory containing the Dockerfile
