CREATE TABLE pin (
    id INT AUTO_INCREMENT PRIMARY KEY,
    lat FLOAT NOT NULL,
    lng FLOAT NOT NULL
);

CREATE TABLE cat (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    `desc` VARCHAR(120) NOT NULL,
    pin_id INT NOT NULL,
    FOREIGN KEY (pin_id) REFERENCES pin(id)
);


